### ISSUE TITLE
New Feature Ignore URLs 

### ISSUE THREAD

**Issue by zg3d** [tonyvugithub/GoURLsCheckerCLI#11]
Hey, I wanted to add a flag that would allow this cli tool to ignore certain urls 
For Example
` ./linkDetector -i url-to-ignore.txt urls.html`

This command would ignore all urls in the text file when searching through the html file.

**Comment by tonyvugithub** [comment]
Great! Thanks! Please go ahead and implement it,

**Comment by zg3d** [comment]
https://github.com/zg3d/GoURLsCheckerCLI/tree/issue-11
Working solution here

**Comment by tonyvugithub** [comment]
Hi @zg3d , Thanks for the commit. I have tested your code locally and merged to my master. The final commit could be found here [93f96f3](https://github.com/tonyvugithub/GoURLsCheckerCLI/commit/93f96f39e57e309c14137a2eb8c7709ac715c2fc)
